name: hello self hosted runner

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: my-runner-123
    steps:
      - name: Hello world action
        run: echo "Hello world from self hosted runner"
